### PR TITLE
Add a dummy CI job for master

### PR DESCRIPTION
**Pull request by jonas-schievink**
This hopefully fixes the badge

### CODE REVIEW

**Comment by adamgreig** [comment]
I think this would successfully force the badge to "build OK", but if anyone actually looked at the build it would just be running `true`. I appreciate bors means we can't have pushed to master without it passing tests, but for the sake of a few seconds more Travis runtime we could just make .travis.yml look like:

```yaml
language: rust
matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
￼     - rust: nightly
￼
￼ branches:
￼   only:
￼     - master
    - staging
    - trying
```

and thereby build on pushes to master as well as pull requests.

**Comment by jonas-schievink** [comment]
Works for me. I wanted to preserve CI resources since they're shared across the entire organization.

**Review by reitermarkus — APPROVED** [review]

**Review by therealprof — APPROVED** [review]
LGTM

**Pull request merged**
