### PR TITLE
Some work towards 1.0

### PR DESCRIPTION
**Pull request by jonas-schievink**
Part of https://github.com/rust-embedded/r0/issues/9

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Looks like this repo isn't yet in the highfive config, so I opened https://github.com/rust-lang/highfive/pull/244. Will assign someone manually.

**Comment by therealprof** [comment]
Yeah, I was still fighting for bors to pick it up. Seems that it now at least shows up in the dashboard.

**Comment by therealprof** [comment]
bors ping

**Comment by therealprof** [comment]
bors try

**Review by adamgreig — APPROVED** [review]

**Comment by adamgreig** [comment]
This looks fine. I wonder if it might be helpful to specifically call out which types implement `T` in the zeroing functions' docstrings, since it's a short and final list?

**Comment by therealprof** [comment]
bors r=adamgreig

**Pull request merged**
